ACTION_SPACE_CONFIG: v0
AC_FREQ_RATIO: 4
ADDITIONAL_OBJECT_PATHS: []
AGENTS: ['AGENT_0']
AGENT_0:
  HEIGHT: 1.5
  IS_SET_START_STATE: False
  RADIUS: 0.5
  SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  START_POSITION: [0, 0, 0]
  START_ROTATION: [0, 0, 0, 1]
ARM_DEPTH_SENSOR:
  HEIGHT: 480
  HFOV: 90
  MAX_DEPTH: 10.0
  MIN_DEPTH: 0.0
  NORMALIZE_DEPTH: True
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  SENSOR_SUBTYPE: PINHOLE
  TYPE: HabitatSimDepthSensor
  UUID: robot_arm_depth
  WIDTH: 640
ARM_REST: [0.6, 0.0, 0.9]
ARM_RGB_SENSOR:
  HEIGHT: 480
  HFOV: 90
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  SENSOR_SUBTYPE: PINHOLE
  TYPE: HabitatSimRGBSensor
  UUID: robot_arm_rgb
  WIDTH: 640
AUDIO:
  BINAURAL_RIR_DIR: data/binaural_rirs
  CROSSFADE: True
  EVERLASTING: True
  GRAPH_FILE: graph.pkl
  HAS_DISTRACTOR_SOUND: False
  METADATA_DIR: data/metadata
  POINTS_FILE: points.txt
  RIR_SAMPLING_RATE: 16000
  SCENE: 
  SOURCE_SOUND_DIR: data/sounds/1s_all
AUTO_SLEEP: False
CONCUR_RENDER: False
CONTINUOUS_VIEW_CHANGE: True
CREATE_RENDERER: False
CTRL_FREQ: 120.0
DEBUG_RENDER: False
DEBUG_RENDER_GOAL: True
DEFAULT_AGENT_ID: 0
DEPTH_SENSOR:
  HEIGHT: 512
  HFOV: 90
  MAX_DEPTH: 10.0
  MIN_DEPTH: 0.0
  NORMALIZE_DEPTH: True
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  SENSOR_SUBTYPE: PINHOLE
  TYPE: HabitatSimDepthSensor
  WIDTH: 512
EE_LINK_NAME: None
EQUIRECT_DEPTH_SENSOR:
  HEIGHT: 480
  MAX_DEPTH: 10.0
  MIN_DEPTH: 0.0
  NORMALIZE_DEPTH: True
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  TYPE: HabitatSimEquirectangularDepthSensor
  WIDTH: 640
EQUIRECT_RGB_SENSOR:
  HEIGHT: 480
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  TYPE: HabitatSimEquirectangularRGBSensor
  WIDTH: 640
EQUIRECT_SEMANTIC_SENSOR:
  HEIGHT: 480
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  TYPE: HabitatSimEquirectangularSemanticSensor
  WIDTH: 640
FISHEYE_DEPTH_SENSOR:
  ALPHA: 0.57
  FOCAL_LENGTH: [364.84, 364.86]
  HEIGHT: 480
  MAX_DEPTH: 10.0
  MIN_DEPTH: 0.0
  NORMALIZE_DEPTH: True
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  PRINCIPAL_POINT_OFFSET: None
  SENSOR_MODEL_TYPE: DOUBLE_SPHERE
  TYPE: HabitatSimFisheyeDepthSensor
  WIDTH: 640
  XI: -0.27
FISHEYE_RGB_SENSOR:
  ALPHA: 0.57
  FOCAL_LENGTH: [364.84, 364.86]
  HEIGHT: 640
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  PRINCIPAL_POINT_OFFSET: None
  SENSOR_MODEL_TYPE: DOUBLE_SPHERE
  TYPE: HabitatSimFisheyeRGBSensor
  WIDTH: 640
  XI: -0.27
FISHEYE_SEMANTIC_SENSOR:
  ALPHA: 0.57
  FOCAL_LENGTH: [364.84, 364.86]
  HEIGHT: 640
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  PRINCIPAL_POINT_OFFSET: None
  SENSOR_MODEL_TYPE: DOUBLE_SPHERE
  TYPE: HabitatSimFisheyeSemanticSensor
  WIDTH: 640
  XI: -0.27
FORWARD_STEP_SIZE: 0.25
GRASP_IMPULSE: 1000.0
GRID_SIZE: 1.0
HABITAT_SIM_V0:
  ALLOW_SLIDING: True
  ENABLE_PHYSICS: False
  FRUSTUM_CULLING: True
  GPU_DEVICE_ID: 0
  GPU_GPU: False
  LEAVE_CONTEXT_WITH_BACKGROUND_RENDERER: False
  PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
HEAD_DEPTH_SENSOR:
  HEIGHT: 480
  HFOV: 90
  MAX_DEPTH: 10.0
  MIN_DEPTH: 0.0
  NORMALIZE_DEPTH: True
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  SENSOR_SUBTYPE: PINHOLE
  TYPE: HabitatSimDepthSensor
  UUID: robot_head_depth
  WIDTH: 640
HEAD_RGB_SENSOR:
  HEIGHT: 480
  HFOV: 90
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  SENSOR_SUBTYPE: PINHOLE
  TYPE: HabitatSimRGBSensor
  UUID: robot_head_rgb
  WIDTH: 640
HOLD_THRESH: 0.09
IK_ARM_URDF: data/robots/hab_fetch/robots/fetch_onlyarm.urdf
LAG_OBSERVATIONS: 0
LOAD_OBJS: False
NEEDS_MARKERS: True
NUM_GOALS: 2
REQUIRES_TEXTURES: True
RGB_SENSOR:
  HEIGHT: 512
  HFOV: 90
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  SENSOR_SUBTYPE: PINHOLE
  TYPE: HabitatSimRGBSensor
  WIDTH: 512
ROBOT_JOINT_START_NOISE: 0.0
ROBOT_TYPE: FetchRobot
ROBOT_URDF: data/robots/hab_fetch/robots/hab_fetch.urdf
SCENE: data/scene_datasets/mp3d/gxdoqLR6rwA/gxdoqLR6rwA.glb
SCENE_DATASET: default
SCENE_OBSERVATION_DIR: data/scene_observations
SEED: 100
SEMANTIC_SENSOR:
  HEIGHT: 480
  HFOV: 90
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  SENSOR_SUBTYPE: PINHOLE
  TYPE: HabitatSimSemanticSensor
  WIDTH: 640
STEP_PHYSICS: True
STEP_TIME: 0.25
THIRD_DEPTH_SENSOR:
  HEIGHT: 480
  HFOV: 90
  MAX_DEPTH: 10.0
  MIN_DEPTH: 0.0
  NORMALIZE_DEPTH: True
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  SENSOR_SUBTYPE: PINHOLE
  TYPE: HabitatSimDepthSensor
  UUID: robot_third_rgb
  WIDTH: 640
THIRD_RGB_SENSOR:
  HEIGHT: 480
  HFOV: 90
  ORIENTATION: [0.0, 0.0, 0.0]
  POSITION: [0, 1.25, 0]
  SENSOR_SUBTYPE: PINHOLE
  TYPE: HabitatSimRGBSensor
  UUID: robot_third_rgb
  WIDTH: 640
TILT_ANGLE: 15
TURN_ANGLE: 10
TYPE: ContinuousSoundSpacesSim
UPDATE_ROBOT: True
USE_RENDERED_OBSERVATIONS: False
USE_SYNC_VECENV: False
VIEW_CHANGE_FPS: 10